[general]
import = [
    "~/.config/alacritty/themes/themes/carbonfox.toml"
]

[env]
TERM = "xterm-256color"

[window]
startup_mode = "Fullscreen"
decorations = "None"
opacity = 0.7
padding = { x = 16 , y = 16 }

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

size = 14

[font.offset]
x = 0
y = 1

[terminal.shell]
program = "/bin/bash"
args = ["-l"]
